### ISSUE TITLE
App not start at windows with newer java versions (tested 12,13)

### ISSUE THREAD

**Issue by mosling** [violetumleditor/violetumleditor#58]
With version 9 but I'm not sure the installation doesn't differentiate between JDK and JRE which is fantastic.

I identified that update the launch4j artifact to version 1.7.25 will work at my windows 10 system.

Can you update and check this, thanks.

**Comment by mireiner** [comment]
I can confirm this. Violet UML doesn't work with JAVA 12 and 13. Because of that users that got JAVA 12 or 13 installed have to install JAVA 8 for Violet UML also. That's not an ideal solution. We all know that older JAVA version are not future proof because of the security risk they will bring sooner or later.

Please do an new Violet UML build using JAVA 12 or 13. At least as a alternative version for users that got new JAVA version installed. Thank you!

**Comment by alexdp** [comment]
OK, thank you for this feedback. I'll try to make an update this week.

**Comment by patrickuhlmann** [comment]
I needed to run violet quickly to view one file. The easiest way I found was downloading the current jar and using docker like that:

`xhost +
sudo docker run --rm -ti --net=host --ipc=host -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --env="QT_X11_NO_MITSHM=1" -v "$PWD":/mnt maven:3.5.0-jdk-8 java -jar "/mnt/violetumleditor-3.0.0.jar"`

**Comment by alexdp** [comment]
Thank you for this great proposal. I’m currently working on this issue which is due to a dépendency on a restricted java display class module called during xstream serialization. I need to remove this dependency on graph model. Kind regards.

**Comment by alexdp** [comment]
Hi, 

Violet is now compiled with Java 17. I hope that you will be able to use it again in better conditions.

Kind regards,
Alex
